<?php

namespace AppBundle\Repository;

/**
 * CoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCoachIdByName($coachName){
        $qb = $this->createQueryBuilder('c')
        ->where('c.name = :coachname')
        ->setParameter('coachname', $coachName);
    
        // $dql = $qb->getDQL();
        $result = $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();

        return $result->getId();
    }
}
