<?php

namespace AppBundle\Repository;

/**
 * JourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneeRepository extends \Doctrine\ORM\EntityRepository
{
}
