<?php

namespace AppBundle\Repository;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDerniereSaison(){
        return $this->createQueryBuilder('s')
        ->orderBy('s.id','DESC')
        ->setMaxResults(1)
        ->getQuery()
        ->getSingleResult();
    }
}
