<?php

namespace AppBundle\Repository;

/**
 * TypeCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
